<?php

/**
 * @var \Intern\Hospital\Block\Display $block
 */

echo $block->dataHospital();

?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}

</style>

<table>
    <tr>
        <th class="post_id">Id</th>
        <th class="name">Name</th>
        <th class="address">Address</th>
        <th class="telephone">Telephone</th>
    </tr>
    <?php
    $enable = $block->getEnable();
    if ($enable) {
        foreach ($block->getPostCollection() as $key => $post) {
            echo '<tr>
                    <td>' . $post->getPostId() . '</td>
                    <td>' . $post->getName() . '</td>
                    <td>' . $post->getAddress() . '</td>
                    <td>' . $post->getTelephone() . '</td>
                  </tr>';
        }
    }
    ?>
</table>

</body>
</html>
